=== Trickstersmind/ehealth.api/specs/json_schemas/new_legal_entity_schema.json
{
   "$schema":"http://json-schema.org/draft-04/schema#",
   "definitions":{
      "phone":{
         "type":"object",
         "properties":{
            "type":{
               "type":"string",
               "description":"Dictionary: PHONE_TYPE"
            },
            "number":{
               "type":"string",
               "pattern":"^\\+38[0-9]{10}$"
            }
         },
         "required":[
            "type",
            "number"
         ],
         "additionalProperties":false
      },
      "document":{
         "type":"object",
         "properties":{
            "type":{
               "type":"string",
               "description":"Dictionary: DOCUMENT_TYPE"
            },
            "number":{
               "type":"string"
            }
         },
         "required":[
            "type",
            "number"
         ],
         "additionalProperties":false
      },
      "address":{
         "type":"object",
         "properties":{
            "type":{
               "type":"string",
               "description":"Dictionary: ADDRESS_TYPE"
            },
            "country":{
               "type":"string"
            },
            "area":{
               "type":"string"
            },
            "region":{
               "type":"string"
            },
            "settlement":{
               "type":"string"
            },
            "settlement_type":{
               "type":"string"
            },
            "settlement_id":{
               "type":"string"
            },
            "street_type":{
               "type":"string"
            },
            "street":{
               "type":"string"
            },
            "building":{
               "type":"string",
               "pattern":"^[0-9]{1,3}(([ \\-]{1})?(?![ЫЪЭЁыъэё])[А-ЯҐЇЄа-яґїє]{1})?((\\s)?(\\|/)(\\s)?[0-9]{1,3}(([ \\-]{1})?(?![ЫЪЭЁыъэё])[А-ЯҐЇЄа-яґїє]{1})?)?$"
            },
            "apartment":{
               "type":"string"
            },
            "zip":{
               "type":"string",
               "pattern":"^[0-9]{5}$"
            }
         },
         "required":[
            "type",
            "country",
            "settlement_id",
            "building"
         ],
         "additionalProperties":false
      }
   },
   "type":"object",
   "properties":{
      "name":{
         "type":"string",
         "pattern":"^(?!.*[ЫЪЭЁыъэё@%&$^#])[a-zA-ZА-ЯҐЇІЄа-яґїіє0-9№\\\"!\\^\\*)\\]\\[(._-].*$"
      },
      "short_name":{
         "type":"string"
      },
      "public_name":{
         "type":"string"
      },
      "type":{
         "type":"string",
         "enum":[
            "MSP"
         ]
      },
      "owner_property_type":{
         "type":"string",
         "description":"Dictionary: OWNER_PROPERTY_TYPE"
      },
      "legal_form":{
         "type":"string",
         "description":"Dictionary: LEGAL_FORM"
      },
      "edrpou":{
         "type":"string",
         "pattern":"^[0-9]{8,10}$"
      },
      "kveds":{
         "type":"array",
         "items":{
            "type":"string",
            "enum":[
               "86.10",
               "86.21",
               "86.22",
               "86.90"
            ]
         },
         "minItems":1
      },
      "addresses":{
         "type":"array",
         "items":{
            "$ref":"#/definitions/address"
         },
         "minItems":1
      },
      "phones":{
         "type":"array",
         "items":{
            "$ref":"#/definitions/phone"
         },
         "minItems":1
      },
      "email":{
         "type":"string",
         "format":"email"
      },
      "owner":{
         "type":"object",
         "properties":{
            "first_name":{
               "type":"string"
            },
            "last_name":{
               "type":"string"
            },
            "second_name":{
               "type":"string"
            },
            "position":{
               "type":"string",
               "description":"Dictionary: POSITION"
            },
            "tax_id":{
               "type":"string",
               "pattern":"^[0-9]{8,10}$"
            },
            "birth_date":{
               "type":"string",
               "format":"date"
            },
            "gender":{
               "type":"string",
               "description":"Dictionary: GENDER"
            },
            "email":{
               "type":"string",
               "format":"email"
            },
            "documents":{
               "type":"array",
               "items":{
                  "$ref":"#/definitions/document"
               },
               "minItems":1
            },
            "phones":{
               "type":"array",
               "items":{
                  "$ref":"#/definitions/phone"
               },
               "minItems":1
            }
         },
         "required":[
            "first_name",
            "last_name",
            "position",
            "tax_id",
            "birth_date",
            "gender",
            "email"
         ]
      },
      "medical_service_provider":{
         "type":"object",
         "properties":{
            "licenses":{
               "type":"array",
               "items":{
                  "type":"object",
                  "properties":{
                     "license_number":{
                        "type":"string"
                     },
                     "issued_by":{
                        "type":"string"
                     },
                     "issued_date":{
                        "type":"string",
                        "format":"date"
                     },
                     "expiry_date":{
                        "type":"string",
                        "format":"date"
                     },
                     "kved":{
                        "type":"string",
                        "enum":[
                           "86.10",
                           "86.21",
                           "86.22",
                           "86.90"
                        ]
                     },
                     "what_licensed":{
                        "type":"string"
                     }
                  },
                  "required":[
                     "license_number",
                     "issued_date"
                  ]
               },
               "minItems":1
            },
            "accreditation":{
               "type":"object",
               "properties":{
                  "category":{
                     "type":"string",
                     "description":"Dictionary: ACCREDITATION_CATEGORY"
                  },
                  "issued_date":{
                     "type":"string",
                     "description":"02-28 (string, required) - дата видачі",
                     "format":"date"
                  },
                  "expiry_date":{
                     "type":"string",
                     "description":"02-28 (string, optional)",
                     "format":"date"
                  },
                  "order_no":{
                     "type":"string",
                     "description":"номер наказу МОЗ"
                  },
                  "order_date":{
                     "type":"string",
                     "description":"02-28 (string, required) - дата наказу МОЗ",
                     "format":"date"
                  }
               },
               "required":[
                  "category",
                  "order_no"
               ]
            }
         },
         "required":[
            "accreditation"
         ]
      },
      "status":{
         "type":"string",
         "enum":[
            "VERIFIED",
            "DECLINED",
            "VERIFICATION_EXP"
         ]
      },
      "security":{
         "type":"object",
         "properties":{
            "redirect_uri":{
               "type":"string",
               "format":"uri",
               "pattern":"^https?:\/\/.+"
            }
         },
         "required":[
            "redirect_uri"
         ]
      },
      "public_offer":{
         "type":"object",
         "properties":{
            "consent":{
               "type":"boolean",
               "enum":[
                  true
               ]
            },
            "consent_text":{
               "type":"string"
            }
         },
         "required":[
            "consent",
            "consent_text"
         ]
      }
   },
   "required":[
      "name",
      "type",
      "owner_property_type",
      "legal_form",
      "edrpou",
      "kveds",
      "addresses",
      "phones",
      "email",
      "owner",
      "medical_service_provider",
      "security",
      "public_offer"
   ],
   "additionalProperties":false
}

=== Trickstersmind/ehealth.api/apps/il/test/data/legal_entity.json
{
  "name": "Клініка Борис",
  "short_name": "Борис",
  "public_name": "Борис",
  "type": "MSP",
  "owner_property_type": "STATE",
  "legal_form": "ПІДПРИЄМЕЦЬ",
  "edrpou": "37367387",
  "kveds": [
    "86.10"
  ],
  "addresses": [
    {
      "type": "REGISTRATION",
      "country": "UA",
      "area": "Житомирська",
      "region": "Бердичівський",
      "settlement": "Київ",
      "settlement_type": "CITY",
      "settlement_id": "dsdafdf",
      "street": "вул. Ніжинська",
      "building": "15-В",
      "apartment": "23",
      "zip": "02090"
    }
  ],
  "phones": [
    {
      "type": "MOBILE",
      "number": "+380503410870"
    }
  ],
  "email": "email@example.com",
  "owner": {
    "first_name": "Петро",
    "last_name": "Іванов",
    "second_name": "Миколайович",
    "position": "лікар",
    "tax_id": "3067305998",
    "birth_date": "1991-08-19",
    "gender": "MALE",
    "email": "email@example.com",
    "documents": [
      {
        "type": "PASSPORT",
        "number": "120518"
      }
    ],
    "phones": [
      {
        "type": "MOBILE",
        "number": "+380503410870"
      }
    ]
  },
  "medical_service_provider": {
    "licenses": [
      {
        "license_number": "fd123443",
        "issued_by": "Кваліфікацйна комісія",
        "issued_date": "1991-08-19",
        "expiry_date": "1991-08-19",
        "active_from_date": "1991-08-19",
        "order_no": "fd123443",
        "what_licensed": "реалізація наркотичних засобів"
      }
    ],
    "accreditation": {
      "category": "ДРУГА",
      "issued_date": "1991-08-19",
      "expiry_date": "1991-08-19",
      "order_no": "fd123443",
      "order_date": "1991-08-19"
    }
  },
  "security": {
    "redirect_uri": "http://example.com/redirect_uri"
  },
  "public_offer": {
    "consent": true,
    "consent_text": "Consent text"
  }
}
